### ISSUE TITLE
undefined reference to `pqxx::argument_error::argument_error`

### ISSUE THREAD

**Issue by Neofitum** [jtv/libpqxx#732]
Hello there! I have got some linking error:

`` /usr/bin/ld: /tmp/ccadqyKa.o: in function `pqxx::internal::(anonymous namespace)::throw_for_encoding_error(char const*, char const*, unsigned long, unsigned long)':
db.cpp:(.text+0x1dc): undefined reference to `pqxx::argument_error::argument_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::source_location)'
/usr/bin/ld: /tmp/ccpFKSJv.o: in function `pqxx::internal::(anonymous namespace)::throw_for_encoding_error(char const*, char const*, unsigned long, unsigned long)':
echo.cpp:(.text+0x1dc): undefined reference to `pqxx::argument_error::argument_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::source_location)'
/usr/bin/ld: /tmp/ccJw3CDF.o: in function `pqxx::internal::(anonymous namespace)::throw_for_encoding_error(char const*, char const*, unsigned long, unsigned long)':
main.cpp:(.text+0x1dc): undefined reference to `pqxx::argument_error::argument_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::source_location)'
collect2: error: ld returned 1 exit status``

As I see my source doesn't matter. It comes from the header <pqxx/pqxx>
Also both variants give the same error:
-lpqxx -lpq
/usr/local/lib/libpqxx.a -lpq

g++ (Debian 13.2.0-1) 13.2.0
psql (PostgreSQL) 15.4 (Debian 15.4-1)

Any advice please?

**Comment by Neofitum** [comment]
btw, I did standard building of the lib:

> ./configure --disable-shared
> make
> sudo make install

**Comment by tt4g** [comment]
There are several possible causes of link errors.
For example, different library versions, different C++ versions, or different linked standard libraries.

**Comment by Neofitum** [comment]
I have just one version of libpqxx - 7.8.2
My machine has two versions of g++ 10 and 13, but I have set up g++13 by default through "alternatives". 

> different linked standard libraries 

It compiles without "-std=c++20" if I switch off std::chrono::year_month_day variables. 
The app compiles separately with -std=c++20 for std::chrono::year_month_day exclusive of pqxx header and separately with -lpqxx for pqxx header exclusive of std=c++20 and std::chrono::year_month_day, but not all together. So what the conflict of libs is there? Does libpqxx fully(as it is possible for the current compilers) support c++20?

**Comment by tt4g** [comment]
Do you mean mixing multiple C++ versions? It will not work.
The symbols will not match because STL has different features provided by different C++ versions.

> support c++20?
Yes.

**Comment by Neofitum** [comment]
> Do you mean mixing multiple C++ versions? It will not work.

No. I mean my C++ refers to g++13 as default version of the compiler.
c++ -> /usr/bin/g++
g++ -> g++-13
So, there is no mixing. I specify which STL the compiler must use "-std=c++20". And it's works with g++13.

**Comment by tt4g** [comment]
`make` uses the compiler specified by the environment variable `CXX` (https://stackoverflow.com/questions/2969222/make-gnu-make-use-a-different-compiler).
Do you mean that you had set `CXX=/usr/bin/g++`?

And did you specify the environment variable `CXXFLAGS="-std=c++20"` when you built by `make`?
If not, libpqxx is built with C++17 (by default g++13).

Also, any of the environment variables will be referenced when running `. /configure` command.

See also: https://github.com/jtv/libpqxx/blob/7.8.1/BUILDING-configure.md#cheat-sheet

**Comment by jtv** [comment]
My guess is that it's an inconsistency in detected `std::source_location` support.  Probably either the headers are detecting it's there and the source file does not, or the other way around; or there's a mistake that doesn't show up with my compiler version.  I'm trying to reproduce the problem, but I've only got gcc 11 here, and that may be making a difference.

**Comment by jtv** [comment]
@Neofitum I can't reproduce the problem with current Debian unstable (gcc 13).

Is it possible that the location where `make install` installs the library by default, simply isn't in your link path?

**Comment by Enhex** [comment]
I'm getting this error when building pqxx library with `-std=c++17` and the project that uses it with `-std=c++20`.
when the standard versions match the error is gone.

**Comment by KayEss** [comment]
> I'm getting this error when building pqxx library with `-std=c++17` and the project that uses it with `-std=c++20`.

This smells like an ODR violation (IFNDR). Can you compile both with the same version?

**Comment by jtv** [comment]
> when they use the same version (either both using 17 or both using 20) it successfully compiles

That's what I'd expect.  Question is: did a difference in versions sneak into @Neofitum's build?

That can happen, for instance, when setting `CXXFLAGS` during the `make` instead of just the `configure`.

**Comment by Enhex** [comment]
I don't know what his build does, I got this error independently from him.

**Comment by Neofitum** [comment]
Guys, sorry for the delay with answer.
I had to rebuild the lib with the following flags:
`./configure --disable-shared CXX=g++ CXXFLAGS=-std=c++20`

Now, my source compiles together with <pqxx/pqxx>, std::chrono inside and with -std=c++20 flag. 

So, it means the library building must be made with -std=c++20 flag if your compiler gcc version is 13 and\or your compiler supports c++20.

Thank you all and @tt4g

**Comment by jtv** [comment]
Right.  By default you should get whatever your compiler decides.  (I'm a little surprised to be honest to see that that's still C++17 in gcc 13.)

**Comment by FloopCZ** [comment]
For those who came because the latest [Arch linux package](https://gitlab.archlinux.org/archlinux/packaging/packages/libpqxx/-/blob/e265101d2577837f9005454649b42ee2f79d85f5/PKGBUILD) with libpqxx 7.8.1+ suffers from this issue and need a quick fix, here is an updated [PKGBUILD](https://gist.github.com/FloopCZ/8f72194e6102155e6752a61ed8b40d6b) with C++20 flag enabled, although it is hardly a permanent solution.

**Comment by tt4g** [comment]
@acwn1976 Do not get the package from Debian, build libpqxx manually.

**Comment by jtv** [comment]
I agree with what @tt4g said.  The problem with using a prepackaged library in C++ is that you're bound to have different compile settings than those that were used to build the packaged library.

And there's just not much that can be done about it.  It'd be easy to say "just use the compiler's defaults," but those will change with some major compiler upgrades.  And then of course, the defaults may not even be what you need.

**Comment by jtv** [comment]
Alright then.  I'll have to go back to writing more config into a header at configure time.

I'd like to avoid duplicating checks between build systems, of course.  Perhaps I can run the compiler in a way that tells me all defined macros, and sort it out from there in a single python script.

**Comment by jtv** [comment]
I'm experimenting with an approach where a python script generates C++ code which in turn, when compiled and run, spits out a C++ configuration header.  It'll be faster and easier to scale than maintaining all those feature tests, but it will also complicates cross compilation.

**Comment by jtv** [comment]
It's harder than I thought.  It would be relatively easy to generate a C++ file that checks the feature flags; run it through the preprocessor; and then write a config header based on the output.  Should work fine even for cross compilers.

But:
* Autoconf's `AC_PREPROC_IFELSE` does not pass `$CXXFLAGS`, defeating the whole point — preprocessing will happen without knowledge of C++ dialect options.
* CMake seems to have no notion of the preprocessor at all, except for actual source files in the project, only when using "make" as a builder.

Tempted to define my own "the option to turn the compiler into a preprocessor" variable...

I'll continue pushing the other solution I've been working on: generate some C++ code that checks the feature flags,_compile and run it,_ and have that spit out a config header.  Does mean defaulting to all features disabled when cross-compiling, and I have yet to make the thing work for CMake.

**Comment by tt4g** [comment]
@jtv CMake does not include a preprocessor, but you can use other features to do something similar.
It is possible to use an external command as a preprocessor using [`add_custom_target()`](https://cmake.org/cmake/help/v3.28/command/add_custom_target.html) or [`add_custom_command()`](https://cmake.org/cmake/help/v3.28/command/add_custom_command.html).

See: https://stackoverflow.com/a/37862193

It is important to note that CMake's `add_custom_command()` (`add_custom_target()`) executes the command at build time.
If you want to generate source code by command before building pqxx libraries, as in this case, the command to generate source code must be executed before pqxx build, but CMake does not know that.
If the order in which the commands are executed is important, a dependency must be set up between the CMake targets.
CMake will automatically add dependencies for targets that use files generated by a particular target.

For example, look at the following code
`include/pqxx/cxx_features.hxx` is generated with `add_custom_command()`, and `include/pqxx/cxx_features.hxx` is specified in the source code with `add_library(pqxx)`.
This ensures that `include/pqxx/cxx_features.hxx` is generated before the `pqxx` target is built.

```cmake
set(pqxx_cxx_features_header include/pqxx/cxx_features.hxx)
add_custom_command(
  OUTPUT ${pqxx_cxx_features_header}
  COMMAND python tools/generate_checks.py cxx_features.txt --dummy
  DEPENDS tools/generate_checks.py cxx_features.txt
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
)
add_library(pqxx ${SOURCE_FILES} ${pqxx_cxx_features_header})
```

There are other options such as [`configure_file()`](https://cmake.org/cmake/help/v3.28/command/configure_file.html) and [`file(GENERATE)`](https://cmake.org/cmake/help/v3.28/command/file.html#generate), but they would not match this use case.

**Comment by hlmodi** [comment]
I'm currently using GCC 13.1, and I'm building it with vcpkg.

I encountered a similar error related to pqxx::conversion_overrun::conversion_overrun. The std::source_location parameter was enabled in the header but not in the compiled library. 

As a quick and dirty solution (I don't care about std::source_location info), I modified the internal/cxx-features.hxx file by setting #define pqxx_have_source_location to 0 in all cases. 

The problem is definitely somewhere around pqxx_have_source_location.

Hope that helps!

**Comment by jtv** [comment]
@tt4g thanks, I have it down now to the point where it works with autotools, and I just need to get it to work with CMake.

For that, I'll need to mirror what I did for autotools:
* Run a piece of C++ (included in the source tree) through the C++ preprocessor.
* Allow the user to override the preprocessor command — it really ought to be a compiler invocation.
* Pass `$CXXFLAGS` to the preprocessor (mainly to select a C++ version).
* Run a custom python script to post-process the pre-processed piece of C++ code to generate the config header.
* Ensure that the generated config header be installed along with the regular headers.

**Comment by jtv** [comment]
I pretty much don't know how to do any of that with CMake.  Any pointers you could give me?  I know `add_custom_command` is supposed to be relevant, but I really don't know how it fits in.

The preprocessor run and the post-processing need to happen when the user configures a build.  I hope it will help that all this now only happens during that one stage.

**Comment by tt4g** [comment]
@jtv Generating files in the CMake configuration step is a tricky task (compared to autotools).

First, I would like to explain the CMake steps, as I think it is important to familiarize yourself with each step of CMake.
CMake has three main steps: configure-step, generate-step and build-step.
Autotools users would like to think that `. /configure` and `make`, but unfortunately this is not the case.

configure-step: parses `CMakeLists.txt` to check the project structure and defined variables.
generate-step: generates project files for native build tools based on the information obtained by configure-step.
build-step: invokes the native build tool to build the artifact from the generated project file.

> **Tip**
> The following sites explain each step in more detail: https://cgold.readthedocs.io/en/latest/tutorials/cmake-stages.html

It is important to note that CMake generates project files that are buildable by native build tools, but leaves the building to the native build tools.
And since CMake is a cross-platform tool, it does not support tasks that can only be performed with specific build tools.

In autotools, `. /configure` can generate additional files, but the equivalent functionality is not supported by other build tools (for example, Visual Studio IDE does not have the ability to automatically generate files when a project is opened.).
Since all native build tools can generate files, the build commands executed by CMake build-step, `add_custom_command()` and `add_custom_target()`, which generate files in build-step, are commonly used in CMake file generation.

The `add_custom_command()` and `add_custom_target()`, which are commonly used in CMake for file generation, work on all platforms because they utilize the functionality of the native build tools.
However, since they are executed by CMake build-step, they will not work in this case.

The best match for this case would be [`execute_process()`](https://cmake.org/cmake/help/v3.28/command/execute_process.html).
The `execute_process` invokes a command (external process) with CMake configure-step.
The external process can generate files.

> **Note**
> CMake support for the external process is not very good.
> This is because the external process is launched while CMake is reading the project configuration.
>
> The return status of the process must be checked with the `RESULT_VARIABLE` variable: https://stackoverflow.com/questions/52076948/check-exit-status-of-execute-process-in-cmake
>
>    If the command outputs errors to STDOUT and STDERROR, then `OUTPUT_VARIABLE` and `ERROR_VARIABLE` should also be checked.
>
> - Customizing environment variables requires ingenuity: https://stackoverflow.com/questions/62927946/passing-environment-variable-to-the-command-in-cmake-execute-process
>
> The community recommends `add_custom_command` over `execute_process`: https://discourse.cmake.org/t/execute-process-vs-add-custom-command/3286


Another solution that exists in CMake is [`try_compile`](https://cmake.org/cmake/help/v3.28/command/try_compile.html).
`try_compile` is used in https://github.com/jtv/libpqxx/blob/7.8.1/cmake/config.cmake
`try_compile` can be used in combination with [`configure_file`](https://cmake.org/cmake/help/v3.28/command/configure_file.html) to record whether a feature is supported.
The user can control the contents of the file generated by `configure_file` by predefining variables to be set by `try_compile`.

**Comment by jtv** [comment]
@tt4g might it be possible then to use `try_compile` but _not_ for one feature, and instead somehow make it all a script to generate the header file as a side effect?  It's a bit of a hack, but at the same time pretty close to what `try_compile` was intended to do, in terms of when it runs etc.

**Comment by tt4g** [comment]
One method is to set the macro to a variable by `try_compile()` and replace it by `configure_file()`.
This method is used in [cmake/config.cmake](https://github.com/jtv/libpqxx/blob/7.8.1/cmake/config.cmake).

- https://github.com/jtv/libpqxx/blob/21afb0d6ec3d31424df6b7aac04c6b20c55c0a65/cmake/config.cmake#L54-L57
- https://github.com/jtv/libpqxx/blob/21afb0d6ec3d31424df6b7aac04c6b20c55c0a65/include/pqxx/config.h.in#L75-L76
- https://github.com/jtv/libpqxx/blob/21afb0d6ec3d31424df6b7aac04c6b20c55c0a65/cmake/config.cmake#L128-L153

> **Tip**
> Header files to be processed by CMake from [include/pqxx/config.h.in](https://github.com/jtv/libpqxx/blob/7.8.1/include/pqxx/config.h.in) are generated by combining `file(WRITE)` and `file(STRINGS)`

See also: https://stackoverflow.com/questions/70113597/does-filegenerate-resolve-variables

**Comment by jtv** [comment]
> @jtv One method is to set the macro to a variable by `try_compile()` and replace it by `configure_file()`. This method is used in [cmake/config.cmake](https://github.com/jtv/libpqxx/blob/7.8.1/cmake/config.cmake).

But will that work for all of these checks in one go?  I'd like to get out of compiling a separate check for each individual feature.

**Comment by tt4g** [comment]
Since `try_compile()` only records build success or failure in one variable, it cannot check all of them in one build.

If compilation errors do not occur, it may be possible to determine this by outputting a message with `#pragma message` and grep.
But `try_compile()` does not seem to capture STDOUT at compile time, you will have to use `execute_process()`.

Example:

`compile_check.cpp`:

```cpp
#if !defined(__cpp_lib_ssize) || !__cpp_lib_ssize
#pragma message "__cpp_lib_ssize"
#endif

int main()
{
    return 0;
}
```

`CMakeLists.txt`:

```cmake
execute_process(
    COMMAND "<BUILD_COMMAND>"
    RESULT_VARIABLE BUILD_RETURN_CODE
    OUTPUT_VARIABLE BUILD_STDOUT
)

if (BUILD_SUCCESS_OR_FAILURE

if(BUILD_RETURN_CODE AND NOT BUILD_RETURN_CODE EQUAL 0)
  message(FATAL_ERROR "Build failed")
endif()

if(BUILD_STDOUT MATCHES "__cpp_lib_ssize")
    set(SUPPORT_SSIZE TRUE)
end
```

**Comment by jtv** [comment]
I was thinking more along the lines of generating the header as a _side effect._  But I'm giving up on the idea.  I think I'll just have to go with generating individual checks when I run `autogen.sh`.  :-(

Presumably there's a way that I can make `config.cmake` include a generated piece of configuration?

**Comment by tt4g** [comment]
Do you mean generate CMake configuration?
That is possible since CMake is a scripting language.
You can write CMake scripts to a file and then import them with [`include()`](https://cmake.org/cmake/help/v3.28/command/include.html).

**Comment by jtv** [comment]
Thanks @tt4g — yes that's what I meant.  I'll use `include()` then!

**Comment by jtv** [comment]
I think I finally have something working for this: #747.

**Comment by jtv** [comment]
@tt4g, @KayEss — I think this PR solves the problem: #747.  Lots of changes, but it boils down to: the old way of working, but with a bunch of configuration in autoconf/cmake automated, and a new config file so I can easily define feature macros _in the config header_ based on the C++ standard feature test macros.

**Comment by tt4g** [comment]
@jtv I had checked the PR changes several times.
I think we can control the activation C++ features.

**Comment by jtv** [comment]
Thank you!  I just merged it.  Once we get #726 out of the way I think we'll be ready to release 7.9.0.

**Comment by jtv** [comment]
@Neofitum @Enhex @tt4g @FloopCZ @acwn1976 @KayEss Some blockers for the next release have cleared up in recent days, so hoping to release 7.9.0 soon, and hopefully the problem won't happen with that.

However in the grander scale, we're still stuck with the problem that all package managers encourage us to link things together that may or may not actually be compatible, because of different language versions etc.

**Comment by tt4g** [comment]
@jtv I think that compilation options for libraries provided by repositories should be devised in such a way that repository administrators can easily refer to them, if they are supposed to.
It is a well-known fact that C++, unlike C, breaks compatibility due to differences in compile options.
There is a limit to avoiding this problem completely by devising library design.

**Comment by jtv** [comment]
That would certainly help @tt4g!  But even then I think we'd need more.  Because what can you actually _do_ when the builds in your project don't match up?  You'd need multiple builds of every single library.  And the matrix of ABI-sensitive build options that would drive the list of builds could be large, irregular, and variable.

The only way out that I see is to "go Gentoo" and just recompile everything every time.

**Comment by tt4g** [comment]
@jtv What I wanted to convey was "I think repository administrators should also provide tips on how to avoid problems like this one, since the library's efforts alone are limited".
If the repository does not tell us the C++ version of the library it provides when it is built, there will be no end to the number of users who encounter errors when using a different C++ version of the project than the library.

Not all users who retrieve libraries from repositories are familiar with building C++, so I feel a little bad asking them to build libraries they are unfamiliar with themselves to isolate the cause.

**Comment by jtv** [comment]
Good point @tt4g.  Makes me wonder what we could do to make this easier on people.  ISTR CMake and `configure` both leave some traces of the build config, but it'd be nice to have a standardised, uniform, concise place to look this up.

**Comment by tt4g** [comment]
@jtv As far as I know, the most famous way to check build options is `phpinfo()` (PHP).
It seems that `phpinfo()` records variables such as `CXX` and `CXX_FLAGS` referenced at build time without the `make` command.
This is not an easy method to provide, as the library provider manually records variables using the preprocessor.
