### ISSUE TITLE
'strnlen_s' was not declared in this scope

### ISSUE THREAD

**Issue by theblackwidower** [jtv/libpqxx#451]
Tried creating a project in Qt Creator that uses this library. Was running some of the example code as a test, modified to work with a database I already had running. It worked fine when I tried running this code in Visual Studio, but not in Qt Creator. Now, I was able to trace this error to the compiler being MinGW. But I don't know why it's happening. 

I noticed there was some kind of precompiler code that I guessed wasn't triggering. So I also tried just removing the code that I figured wasn't supposed to run, and left the code that was. It actually made the problem worse. Around 100 errors popped up in that case.

Anyway, I placed the relevant error message down below. 

```
C:\Users\thebl\GitHub\vcpkg\installed\x64-windows\include\pqxx\internal\conversions.hxx:39: error: 'strnlen_s' was not declared in this scope
In file included from C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/strconv.hxx:402,
                 from C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/binarystring.hxx:22,
                 from C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/binarystring:4,
                 from C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/pqxx:3,
                 from C:/Users/thebl/GitHub/DatabaseTest/main.cpp:2:
C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/internal/conversions.hxx: In function 'std::size_t pqxx::internal::shortcut_strlen(const char*, std::size_t)':
C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/internal/conversions.hxx:39:10: error: 'strnlen_s' was not declared in this scope
   return strnlen_s(text, max);
          ^~~~~~~~~
C:/Users/thebl/GitHub/vcpkg/installed/x64-windows/include/pqxx/internal/conversions.hxx:39:10: note: suggested alternative: 'strnlen'
   return strnlen_s(text, max);
          ^~~~~~~~~
          strnlen
```

**Comment by tt4g** [comment]
Can you use latest release v7.5.2?
`strnlen_s` was removed in v7.5.0 (this commit 899d148f6a7a3e4dabac1ba4f6eb6e4f709e3bac).

**Comment by jtv** [comment]
Did you re-configure the build when building with a different compiler?
The configure stage (in your case probably cmake) checks out what features
your compiler environment offers.  It stores that information in config-*
headers in your build environment.

If your compiler does not have strnlen_s, the build should not detect that
that feature is present, and then the libpqxx code won't use it.  But if
you're building with two compiler environments, you must configure each of
those builds separately, because each environment will have a different
feature set.

**Comment by theblackwidower** [comment]
Well, I was using vcpkg for both. Otherwise, I actually rebuilt the thing from scratch, merely copy-pasting the relevant contents of the Cmake and c++ files. Do I need to clear out something in vcpkg or something?

**Comment by tt4g** [comment]
Usually, libraries built with different compilers cannot be used.
This is because the features supported by the compiler and the binaries generated are not compatible.

If you want to use a combination of Qt Creator and MinGW, please build pqxx from scratch in the same environment or change the compiler used by Qt Creator to Visual Studio compiler.

**Comment by theblackwidower** [comment]
Okay, that's fair. Now, how do I do that? Because I can clear my project's build directory, but obviously that won't do any good if it's referencing binaries outside of that.

**Comment by jtv** [comment]
It's not an environment I'm too familiar with, I'm afraid; but the good
news is that there should be very few dependencies.  The libpqxx library
should depend only on the libpq library.

What was happening in your case though seems to happen even before the
stage where libraries get linked together.  So your initial problem at
least ought to go away if you clear out the build directory, or just do the
MSVC and MinGW builds in completely separate directories.  The two
compilers are very different, with different capabilities and different
standard libraries - and as @tt4g points out, producing binaries that can't
link together.

That last point means that you can't use a libpqxx built with MSVC from an
application built with MinGW, or vice versa.  So if you were using a
pre-packaged libpqxx, then the choice of compiler is really an implicit
configuration choice made by the packagers.  You may have to build your own
libpqxx from source.

**Comment by theblackwidower** [comment]
Was experimenting with this, and clearing out the entire vcpkg directory and starting from scratch didn't work because it turns out they actually cache the binaries, and that was preserved for some reason. I'll figure this out. Thanks for your help. Hope someone else can offer some additional insight, however.

**Comment by tt4g** [comment]
If you don't want to stick with MinGW, you can use Visual Studio with Qt Creator.

There is an official document on how to use the Visual Studio compiler with Qt Creator.
https://doc.qt.io/qtcreator/creator-tool-chains.html

Specify the compiler added in Kits, then your project should be built with the Visual Studio compiler.
https://doc.qt.io/qtcreator/creator-targets.html

**Comment by theblackwidower** [comment]
I think I tried that briefly, it didn't work. But I found another solution. Simply by using a different 'triplet' I'm able to install the correctly compiled version. 
`vcpkg install libpqxx:x64-mingw-dynamic`
I also added this to the CMake configuration variables:
`VCPKG_TARGET_TRIPLET:STRING=x64-mingw-dynamic`
And that worked. Compiles fine now. After the hour or so it took to install.

**Comment by jtv** [comment]
Yes, they're effectively different systems!  Glad you got it sorted.
