### ISSUE TITLE
Broken package of Libpqxx on conancenter

### ISSUE THREAD

**Issue by Orange-hanter** [jtv/libpqxx#564]
I'm not sure if I'm writing to the right place, but I found a problem in the library when used through the conan package manager.
The file associated with #include<pqxx/pqxx> is different from the file in the github repository.

Next lines are missing:
#include "pqxx/internal/result_iterator.hxx"
#include "pqxx/internal/result_iter.hxx"
#include "pqxx/row.hxx"

**Comment by jtv** [comment]
Sounds like just a version difference.  Those particular `#include` statements have changed very recently in libpqxx.

**Comment by harmic** [comment]
We've started having compile failure when using the `7.7.2` tagged version:

```
dbalignment.cpp: In member function ‘void Itk::Ispdb::DbAlignment::defineSchema(const Itk::Ispdb::Schema&, bool)’:
dbalignment.cpp:459:37: error: variable ‘pqxx::result::const_iterator row’ has initializer but incomplete type
   for (pqxx::result::const_iterator row : tx.exec(
                                     ^~~
dbalignment.cpp:462:4: error: invalid use of incomplete type ‘using const_iterator = class pqxx::const_result_iterator {aka class pqxx::const_result_iterator}’
    ) ) {
    ^
In file included from /usr/include/pqxx/errorhandler.hxx:20:0,
                 from /usr/include/pqxx/connection.hxx:36,
                 from /usr/include/pqxx/connection:7,
                 from ../../include/itk/ispdb/dbhandle.h:24,
                 from ../../include/itk/ispdb/dbalignment.h:25,
                 from dbalignment.cpp:21:
/usr/include/pqxx/types.hxx:50:7: note: forward declaration of ‘using const_iterator = class pqxx::const_result_iterator {aka class pqxx::const_result_iterator}’
 class const_result_iterator;
       ^~~~~~~~~~~~~~~~~~~~~
```

We are using an RPM that we built ourselves from the 7.7.2 source.

After inserting the following lines in `/usr/include/pqxx/pqxx`:

```
#include "pqxx/internal/result_iterator.hxx"
#include "pqxx/internal/result_iter.hxx"
```

compilation succeeds.

**Comment by bjowi** [comment]
I find that adding an include of <pqxx/result> to your program also helps.

**Comment by harmic** [comment]
Actually the 7.7.2 release seemed to already have pqxx/result included.

**Comment by jtv** [comment]
I radically reorganised the relationship between the headers in 7.7.2.  I think it's structured better now.  Haven't bothered timing it, but I get the impression it compiles faster too.

**Comment by harmic** [comment]
Here is a small reproduction:

```C++
#include <iostream>
#include <pqxx/pqxx>

// Compile with: g++ -o main --std=c++17 -lpqxx main.cpp

int main()
{
  try
  {
    pqxx::connection c;
    pqxx::work w(c);
    for (pqxx::result::const_iterator row: w.exec("SELECT 1")) {
		std::cout << row[0].as<int>() << std::endl;
	}
    w.commit();
  }
  catch (std::exception const &e)
  {
    std::cerr << e.what() << std::endl;
    return 1;
  }
}
```

This fails to compile with this error on the 7.7.2 delivery:

```
main.cpp: In function ‘int main()’:
main.cpp:12:39: error: variable ‘pqxx::result::const_iterator row’ has initializer but incomplete type
     for (pqxx::result::const_iterator row: w.exec("SELECT 1")) {
                                       ^~~
main.cpp:12:61: error: invalid use of incomplete type ‘using const_iterator = class pqxx::const_result_iterator {aka class pqxx::const_result_iterator}’
     for (pqxx::result::const_iterator row: w.exec("SELECT 1")) {
                                                             ^
In file included from /usr/include/pqxx/result.hxx:25:0,
                 from /usr/include/pqxx/binarystring.hxx:22,
                 from /usr/include/pqxx/pqxx:5,
                 from main.cpp:2:
/usr/include/pqxx/types.hxx:50:7: note: forward declaration of ‘using const_iterator = class pqxx::const_result_iterator {aka class pqxx::const_result_iterator}’
 class const_result_iterator;
       ^~~~~~~~~~~~~~~~~~~~~
```

If we add in those two lines I mentioned above in `/usr/include/pqxx/pqxx` then it compiles and works.

@jtv I didn't quite understand - do you mean we now need to include additional headers beyond `<pqxx/pqxx>`? I am guessing we are not supposed to include those internal headers directly.

**Comment by jtv** [comment]
You are correct - don't include the ".hxx" headers yourself.  The
<pqxx/pqxx> one should be enough to cover the entire library.

I don't know conan.  Is it possible that they had a patch for a libpqxx
header, and a conflict caused them to miss an update in the corresponding
libpqxx header from me?

**Comment by Orange-hanter** [comment]
Look at last labelled released version. It doesn't include listed above libraries in pqxx/pqxx header file. So Conan use only last official release of library. I suppose that the problem is in release configuration of pqxx/pqxx
ps:
https://github.com/jtv/libpqxx/archive/refs/tags/7.7.2.tar.gz - that link I found in conan recipe

**Comment by jtv** [comment]
Ahhh, it looks like that last change was too late to make it into the 7.7.2 release.  I'll release 7.7.3!

**Comment by jtv** [comment]
Here you go: the [7.7.3 release](https://github.com/jtv/libpqxx/releases/tag/7.7.3).  Should fix the problem.  My apologies for getting this wrong.

**Comment by jtv** [comment]
I'll close this ticket.  The 7.7.3 release fixes the problem.
