### ISSUE TITLE
pqxx library build error for crosscompiling on linux for Windows target with Mingw64 

### ISSUE THREAD

**Issue by yscontrol** [jtv/libpqxx#336]
I built PostrgeSQL libpq (.dll, .a, ,..) v9.3.6  on ubuntu 14.04 and then tried building libpqxx  v6.2.5 using cmake.   It failed with error below:
[ 35%] Linking CXX shared library libpqxx.dll
CMakeFiles/pqxx_shared.dir/objects.a(connection_base.cxx.obj):connection_base.cxx:(.text+0x8eac): undefined reference to `__imp_select'
collect2: error: ld returned 1 exit status
make[2]: *** [src/libpqxx.dll] Error 1
make[1]: *** [src/CMakeFiles/pqxx_shared.dir/all] Error 2
make: *** [all] Error 
Since PostgreSQL distro  doers not have support for find_PQ.cmake, I replaced find_package with find_library and cmake funds static libpq.a  while I am trying to build for .dll Windows 
I am not sure how to figure out the issue. Changing versions to later is  not desirable as I am porting code that works with v9.3.5 on linux (arm or x86).

**Comment by jtv** [comment]
You should be able to use libpqxx 7.1 with postgres 9.3.5, just not with versions _older_ than 9.3.  You could even use a newer libpq with an older postgres server.  There have been a lot of changes to the CMake build since libpqxx 6.2, so an upgrade may just solve this problem.

Another thing you can try is explicitly link to the Windows `ws2_32` library.  The `configure` build should do this automatically, but I'm not too sure about the CMake build.

**Comment by tt4g** [comment]
@jtv is right.

As far as my search for "undefined reference to `__imp_select'" goes, it seems to be a missing link to `ws2_32`.

pqxx version 6.3.0 and above, `ws2_32` is automatically added to the link target when the CMake target OS is Windows.
However, pqxx 6.2.5 does not automatically add it to the link target (this problem fixed by #126).

The following pqxx 6.3.0 permalink have been added for linking target (this code did not exist earlier than pqxx version 6.2.5):
 
https://github.com/jtv/libpqxx/blob/d6ffb1a13e76995253ef698fb8a6b3d4c6499179/src/CMakeLists.txt#L28-L30

The best solution is to upgrade pqxx version.
Alternatively, add the same code as the above permalink to `CMakeLists.txt` in pqxx 6.2.5.

**Comment by yscontrol** [comment]
Wow, thank you so much!

**Comment by yscontrol** [comment]
Could you please advise if my understanding of 7.1 build process is correct. I have to use custom location (not one of well-knowns) of PostgreSQL In both 6.2.5 and 7.1.0 the CMakeLists.txt attempts to find_package(PostgreSQL REQUIRED) but since it relies on cmake   PostgreSQLConfig.cmake/ postgresql-config.cmake which are not provided with PostgreSQL as it does not have support for CMake fbuild. So custom file would need to be created to use libpqxx CMake build or path to modules would need to to change to avoid using cmake-3.17/Modules/ and use custom FindPostgreSQL/FindPQ.cmake. This is only needed for the sake of setting 1 (or 2 vars) PostgreSQL_LIBRARIES as PostgreSQL_INCLUDE_DIRS could be derived as ../include. So all this could have been done by using find_path or find_library with PATHS set to location of libpq.dll (or .a). Note, aside  from this the find_package(PostgreSQL ..) is being called in multiple places config.cmake and src/CMakeLists.txt (plus 2 code locations in test) and I wonder why not in 1 place. I could bypass 2nd by setting PostgreSQL_FOUND

**Comment by yscontrol** [comment]
Anyway, I 
git co 7.1.0
Then edited CMakeLists.txt: removed REQUIRED for find_package, used find_library with NAMES  libpq.dll pq  which "successfully" found libpqx.a (instead of .dll as I am crosscompiling  for Windows) and the I  set all variables which get set by find_package
`set(PostgreSQL_INCLUDE_DIRS ${PostgreSQL_LIBRARIES}/../include CACHE PATH "PostgreSQL_INCLUDE_DIR" FORCE)
        set(PostgreSQL_FOUND TRUE CACHE BOOL "PostgreSQL package found" FORCE)
        set(PostgreSQL_LIBRARIES ${PQSQL_LIBS} CACHE PATH "libraries needed for linking" FORCE)
        set(PostgreSQL_VERSION_STRING "9.6.3" CACHE STRING "libpq version found" FORCE)
m`
I got 
-- Looking for poll - not found
-- Looking for PQencryptPasswordConn
-- Looking for PQencryptPasswordConn - not found
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating config.h
-- Generating config.h - done
-- Configuring done
-- Generating done
Then I compile failed:
Scanning dependencies of target pqxx
[  0%] Building CXX object src/CMakeFiles/pqxx.dir/array.cxx.obj
In file included from /home/cnh/workspace/framework/libpqxx/include/pqxx/array.hxx:18:0,
                 from /home/cnh/workspace/framework/libpqxx/include/pqxx/array:4,
                 from /home/cnh/workspace/framework/libpqxx/src/array.cxx:16:
/home/cnh/workspace/framework/libpqxx/include/pqxx/internal/encodings.hxx:15:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.

**Comment by tt4g** [comment]
pqxx 7.1.0 required C++17 standard, you don't remove `set(CMAKE_CXX_STANDARD 17)`.
and pqxx 7.x required libpq version 9.3.5 later.

**Comment by yscontrol** [comment]
Thx, but which one is latest supporting C++11 ?

**Comment by tt4g** [comment]
pqxx 6.4.0 (6.4.6 better) supports C++11 standard.

**Comment by yscontrol** [comment]
ok, thx, still question of bypassing find_package and way of cross- building dll remains. 
Also if I use ./configure I could specify path to pg_config but since PostreSQL was built on ubuntu for Windows I am not sure  these version would be valid for cross compiling libpqxx,

**Comment by tt4g** [comment]
Try `set(PostgreSQL_INCLUDE_DIR <PATH_TO_INCLUDE_DIR>)`, `set(PostgreSQL_TYPE_INCLUDE_DIR <PATH_TO_INCLUDE_DIR>)` and `set(PostgreSQL_LIBRARY <PATH_TO_LIBPQ>)` to override `find_package(PostgreSQL)` result.

Example:

```bash
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DPostgreSQL_LIBRARY="<PATH_TO_POSTGRES>/lib/libpq.lib" -DPostgreSQL_INCLUDE_DIR="<PATH_TO_INCLUDE_DIR>\include" -DPostgreSQL_TYPE_INCLUDE_DIR="<PATH_TO_INCLUDE_DIR>\include"
cmake --build . --config Debug --target -j 8
```

Another way, `set(PostgreSQL_ROOT <PATH_TO_POSTGRES>)`.

```bash
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DPostgreSQL_ROOT="<PATH_TO_POSTGRES>"
cmake --build . --config Debug --target -j 8
```

**Comment by yscontrol** [comment]
I just used find_library and set all necessary variables based on that:
`set(PostgreSQL_INCLUDE_DIRS "${PostgreSQL_INCLUDE_DIRS}/include" CACHE PATH "PostgreSQL_INCLUDE_DIR" FORCE)
        set(PostgreSQL_FOUND TRUE CACHE BOOL "PostgreSQL package found" FORCE)
        set(PostgreSQL_LIBRARIES ${PQSQL_LIBS} CACHE PATH "libraries needed for linking" FORCE)
        set(PostgreSQL_VERSION_STRING "9.6.3" CACHE STRING "libpq version found" FORCE)` 
so they all set correctly. However I am getting error:
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting std::optional
-- Detecting std::optional - not supported
-- Detecting std::experimental::optional
-- Detecting std::experimental::optional - not supported
-- Detecting __attribute__ ((const))
-- Detecting __attribute__ ((const)) - supported
-- Detecting __attribute__ ((pure))
-- Detecting __attribute__ ((pure)) - supported
-- Detecting __attribute__ ((visibility))
-- Detecting __attribute__ ((visibility)) - supported
-- Generating config.h
-- Generating config.h - done
-- Configuring done
-- Generating done
-- Build files have been written ...
[  1%] Building CXX object src/CMakeFiles/pqxx_shared.dir/connection.cxx.obj
In file included from /home/mydir/libpqxx/include/pqxx/basic_connection.hxx:23:0,
                 from /home/mydir/libpqxx/include/pqxx/connection.hxx:20,
                 from /home/mydir/libpqxx/include/pqxx/connection:12,
                 from /home/mydir/libpqxx/src/connection.cxx:20:
/home/mydir/libpqxx/include/pqxx/connection_base.hxx: In constructor ‘pqxx::connection_base::connection_base(pqxx::connectionpolicy&)’:
/home/mydir/libpqxx/include/pqxx/connection_base.hxx:739:14: error: invalid initialization of non-const reference of type ‘pqxx::connectionpolicy&’ from an rvalue of type ‘<brace-enclosed initializer list>’
  m_policy{pol}
NOte

**Comment by tt4g** [comment]
What compiler and compiler version?

`pqxx::connectionpolicy&` argument of `pqxx::connection_base` constructor is provided by `pqxx::basic_connection_base::m_policy`.

Problem code:

https://github.com/jtv/libpqxx/blob/b20d2f13cdd74ba4e7f78c7e5d483326197f8f21/include/pqxx/connection_base.hxx#L738-L739

Called by:

https://github.com/jtv/libpqxx/blob/b20d2f13cdd74ba4e7f78c7e5d483326197f8f21/include/pqxx/basic_connection.hxx#L49-L53

But `m_policy` is member variable of `pqxx::basic_connection_base`, it should be able to be an lvalue.
This is not rvalue.

https://github.com/jtv/libpqxx/blob/b20d2f13cdd74ba4e7f78c7e5d483326197f8f21/include/pqxx/basic_connection.hxx#L79

I ran a very similar code in Wandbox and was able to compile it: https://wandbox.org/permlink/OpB5Iqr9jaQb7sfc

It looks like a compiler problem.

**Comment by yscontrol** [comment]
Compiler is mingw64x86_64-w64-mingw32-gcc (GCC) 4.8.2
  running on ubuntu14.0

**Comment by yscontrol** [comment]
Please also look at the question about building .dll & .lib for Windows rather than .a

**Comment by jtv** [comment]
Isn't that a very old compiler?

By the way, MinGW might just be enough of a GNU environment that you could perhaps use the `configure` script instead.

But that's just me talking, as a not-a-CMake-expert.  Thanks once again @tt4g for taking the reins where I'm out of my depth!

**Comment by yscontrol** [comment]
No all computers are "new" but it is common in Embedded dev to cross-build for many different targets and therefore use older OS like ubuntu 14.04 to fulfill all from one setup...
yes, I will try using configure but not sure what else do I need to install for that. The README.md says about configure "It needs to find the C header and the binary" but a) binary and headers are   installed in different dirs under /usr b) postgresql-9.3.6 build has sources for pg_config but since this libpq build was done for Windows target, the executable is a Windows postgresql-9.3.6/./src/bin/pg_config/pg_config.exe and cant run on ubuntu so what exacly libpqxx needs for this  case of crosscompilation?
I also noticed that config/sample-headers/compiler/compiler  has only gcc-7.2  VisualStudio2013 dirs .
Lastly I am not clear with direction "the header files for PostgreSQL need the OpenSSL header files to be installed. If this happens". Where to, and how configure needs to be set to pick them . Again I built PostgreSQL ok without need to add any additional packages.

**Comment by yscontrol** [comment]
Tried and configure fails bc it cant run "pg_config --includedir". There should be accommodation for building in cross-compiled environment. Instead of  pg_config it should find libpq-fe.h or allow  appending to includedir
Found --with-postgres-include arg, set it and failing in 
--with-postgres-include

**Comment by tt4g** [comment]
> Is not this is a problem in the code as missing realm of names dependent on template parameter?

@yscontrol Did you build pqxx 6.3.0? If so, Update pqxx 6.3.1 because this issue fixed: #153

**Comment by yscontrol** [comment]
yes, I upgraded to 6.4.6 and this issue went away. However we are back with the original issue: 
            ^
../include/pqxx/connection_base.hxx: In constructor ‘pqxx::connection_base::connection_base(pqxx::connectionpolicy&)’:
../include/pqxx/connection_base.hxx:739:14: error: invalid initialization of non-const reference of type ‘pqxx::connectionpolicy&’ from an rvalue of type ‘<brace-enclosed initializer list>’
  m_policy{pol}
              ^

**Comment by tt4g** [comment]
@yscontrol I found the following issue reports:

* [c\+\+ \- Why can't I initialize a reference in an initializer list with uniform initialization? \- Stack Overflow](https://stackoverflow.com/questions/10509603/why-cant-i-initialize-a-reference-in-an-initializer-list-with-uniform-initializ)
* [50025 – \[DR 1288\] C\+\+0x initialization syntax doesn't work for class members of reference type](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50025)

It seems to be a bug brought about by the C++11 standard.
It has been modified by the C++14 standard.
And although gcc4 is affected by this bug, it doesn't seem to be a problem if you use gcc 5 (see eXpl0it3r/SmallGameEngine#3).

**Comment by tt4g** [comment]
I can reproduce " invalid initialization of non-const reference of type ..." error with gcc 4.8.5: https://wandbox.org/permlink/mQr8Olis4MLXrH8O

When using gcc 4.9.3, I can compile same code: https://wandbox.org/permlink/aKrhTuuctUA1JUBl

@yscontrol There are two solutions.
The first is to update gcc to at least version 4.9.
The second is to apply a patch that replaces all of the List-initialization in the source code with parentheses.

Example:
```diff
protected:
  explicit connection_base(connectionpolicy &pol) :
-	m_policy{pol}
+	m_policy(pol)
```

**Comment by yscontrol** [comment]
That’s great. As I bound to 4.8.5 by the version of mingw64 supported on
ubuntu14.04, I need to do the replacement. Is there an issue logged for
this fix as I assume it would be found before compiler 4.9.3 was released ?
I just want to better understand the issue and see if script made available
to fix it

**Comment by tt4g** [comment]
> * [c\+\+ \- Why can't I initialize a reference in an initializer list with uniform initialization? \- Stack Overflow](https://stackoverflow.com/questions/10509603/why-cant-i-initialize-a-reference-in-an-initializer-list-with-uniform-initializ)
> * [50025 – \[DR 1288\] C\+\+0x initialization syntax doesn't work for class members of reference type](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50025)

From reading the comments on the above link, I'd say that up to gcc 4.8, It was in compliance with the FDIS (final draft international standard) of C++ standard specification.
gcc 4.8 seemed to behave in accordance with FDIS.
However, problems like this issue have been reported and C++ standard specification has been corrected.
gcc 4.9 and later seemed to behave in accordance with fixed C++ standard specification.

**Comment by yscontrol** [comment]
Many thanks for your investigation, tt4g. I tried changing just one instance flagged above and got next error:
                                                     ^
../include/pqxx/transaction_base.hxx: In constructor ‘pqxx::nontransaction::nontransaction(pqxx::connection_base&, const string&)’:
../include/pqxx/transaction_base.hxx:524:12: error: ‘pqxx::transaction_base::transaction_base(pqxx::connection_base&, bool)’ is protected
   explicit transaction_base(connection_base &c, bool direct=true);
            ^
In file included from ../include/pqxx/nontransaction:6:0,
                 from connection_base.cxx:56:
../include/pqxx/nontransaction.hxx:66:59: error: within this context
     namedclass{"nontransaction", Name}, transaction_base{C} { Begin(); }
                                                           ^
../include/pqxx/nontransaction.hxx:66:59: error: cannot allocate an object of abstract type ‘pqxx::transaction_base’
In file included from ../include/pqxx/nontransaction.hxx:21:0,
                 from ../include/pqxx/nontransaction:6,
                 from connection_base.cxx:56:
../include/pqxx/transaction_base.hxx:136:36: note:   because the following virtual functions are pure within ‘pqxx::transaction_base’:
 class PQXX_LIBEXPORT PQXX_NOVTABLE transaction_base :
                                    ^
../include/pqxx/transaction_base.hxx:147:11: note: 	virtual pqxx::transaction_base::~transaction_base()
   virtual ~transaction_base() =0;     //[t01]
           ^
../include/pqxx/transaction_base.hxx:535:16: note: 	virtual void pqxx::transaction_base::do_begin()
   virtual void do_begin() =0;
                ^
../include/pqxx/transaction_base.hxx:537:18: note: 	virtual pqxx::result pqxx::transaction_base::do_exec(const char*)
   virtual result do_exec(const char Query[]) =0;
                  ^
../include/pqxx/transaction_base.hxx:539:16: note: 	virtual void pqxx::transaction_base::do_commit()
   virtual void do_commit() =0;
                ^
../include/pqxx/transaction_base.hxx:541:16: note: 	virtual void pqxx::transaction_base::do_abort()
   virtual void do_abort() =0;
                ^
connection_base.cxx: In constructor ‘pqxx::internal::reactivation_avoidance_exemption::reactivation_avoidance_exemption(pqxx::connection_base&)’:
connection_base.cxx:1212:21: error: invalid initialization of non-const reference of type ‘pqxx::connection_base&’ from an rvalue of type ‘<brace-enclosed initializer list>’
   m_open{C.is_open()}

**Comment by jtv** [comment]
Have you tried removing the PQXX_NOVTABLE?  The error as given is definitely nonsensical — you can't allocate an object of an abstract type, but _of course_ you should be able to base-class-initialise it.

**Comment by yscontrol** [comment]
How do I do that safely? I see
./include/pqxx/robusttransaction.hxx:30:class PQXX_LIBEXPORT PQXX_NOVTABLE basic_robusttransaction :
./include/pqxx/dbtransaction.hxx:62:class PQXX_LIBEXPORT PQXX_NOVTABLE dbtransaction : public transaction_base
./include/pqxx/tablestream.hxx:26:class PQXX_LIBEXPORT PQXX_NOVTABLE tablestream :
./include/pqxx/notification.hxx:55:class PQXX_LIBEXPORT PQXX_NOVTABLE notification_receiver
./include/pqxx/stream_base.hxx:27:class PQXX_LIBEXPORT PQXX_NOVTABLE stream_base :
./include/pqxx/compiler-public.hxx:60:#define PQXX_NOVTABLE __declspec(novtable)
./include/pqxx/compiler-public.hxx:118:#ifndef PQXX_NOVTABLE
./include/pqxx/compiler-public.hxx:119:#define PQXX_NOVTABLE
./include/pqxx/transaction_base.hxx:136:class PQXX_LIBEXPORT PQXX_NOVTABLE transaction_base :
./include/pqxx/except.hxx:55:class PQXX_LIBEXPORT PQXX_NOVTABLE pqxx_exception
./doc/Doxyfile.in:1058:                         PQXX_NOVTABLE= \

**Comment by jtv** [comment]
It's possible that in your case it already happens, but the simplest way to make sure would be to edit `compiler-public.hxx`, and in line 60, remove the `__declspec(novtable)` part of the line.

**Comment by yscontrol** [comment]
no, line 60 is under

**Comment by yscontrol** [comment]
meanwhile, I tried to build with newer compiler:
x86_64-w64-mingw32-g++ (GCC) 5.3.1 20160211
x86_64-w64-mingw32-gcc (GCC) 5.3.1 20160211
and I am getting error:
/bin/bash ../libtool  --tag=CXX   --mode=compile /usr/bin/x86_64-w64-mingw32-gcc -std=c++11 -DHAVE_CONFIG_H   -I../include -I../include -I/home/mydir/postgresql-9.3.6/install/mingw64/include   -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT util.lo -MD -MP -MF .deps/util.Tpo -c -o util.lo util.cxx
libtool: compile:  /usr/bin/x86_64-w64-mingw32-gcc -std=c++11 -DHAVE_CONFIG_H -I../include -I../include -I/home/mydir/postgresql-9.3.6/install/mingw64/include -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT util.lo -MD -MP -MF .deps/util.Tpo -c util.cxx -o util.o
util.cxx: In function ‘void pqxx::internal::sleep_seconds(int)’:
util.cxx:120:8: error: ‘std::this_thread’ has not been declared
   std::this_thread::sleep_for(std::chrono::seconds(s));
        ^
Makefile:524: recipe for target 'util.lo' failed

**Comment by tt4g** [comment]
> util.cxx:120:8: error: ‘std::this_thread’ has not been declared
> std::this_thread::sleep_for(std::chrono::seconds(s));
> ^

That' s MinGW problem.
MinGW does not support C++11 thread feature on Windows OS.

Maybe this solution will help you: [apt \- How do I install mingw\-std\-threads on Ubuntu? \- Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/410003/how-do-i-install-mingw-std-threads-on-ubuntu)

Another solutions:

* [c\+\+ \- error: 'std::this\_thread' has not been declared \- Stack Overflow](https://stackoverflow.com/questions/13741711/error-stdthis-thread-has-not-been-declared)
* [c\+\+ \- MinGW error: ‘thread’ is not a member of ‘std’ \- Stack Overflow](https://stackoverflow.com/questions/21211980/mingw-error-thread-is-not-a-member-of-std)
* [windows \- cross\-compiling c\+\+11 threads with mingw on linux \- Stack Overflow](https://stackoverflow.com/questions/17625306/cross-compiling-c11-threads-with-mingw-on-linux)

**Comment by yscontrol** [comment]
tt4g, thank you very much , I will have to use cmake /modify libpqxx to include https://github.com/meganz/mingw-std-threads header only lib. However the main approach still requires use of ubuntu 14.04 - gcc 4.8.5 and so resolving issue with "dbtransaction.cxx:45:60: error: cannot allocate an object of abstract type ‘pqxx::transaction_base’
m_start_cmd{generate_set_transaction(rw, IsolationString)}" above or removing the PQXX_NOVTABLE ?

**Comment by tt4g** [comment]
>  removing the PQXX_NOVTABLE ?

Yes. replace `#define PQXX_NOVTABLE __declspec(novtable)` with`#define PQXX_NOVTABLE`.

`__declspec(novtable)` is an extended attribute that, if present, will cause a runtime error. It won't matter if you remove it.

* [novtable \| Microsoft Docs](https://docs.microsoft.com/en-us/cpp/cpp/novtable?view=vs-2019)

@jtv has commented on that as well.: https://github.com/jtv/libpqxx/issues/336#issuecomment-645582631

**Comment by yscontrol** [comment]
@jtv Thank you but such change would not have any effect because 
 line 60 is under _MSC_VER while I am cross-compiling on Linux for Windows
// Workarounds for Microsoft Visual C++
#ifdef _MSC_VER
// Suppress vtables on abstract classes.
#define PQXX_NOVTABLE __declspec(novtable)

**Comment by jtv** [comment]
@yscontrol yes, I'm just bringing it up because sometimes the lines between "Windows" and "MSVC" get a little blurred.  And I've got no other idea why gcc (even version 2.7 if it came to that!) would object to base-class-initialising an abstract class!

**Comment by yscontrol** [comment]
@jtv @tt4g , thanks but is there an easy  way to bypass problematic code without losing main functionality?

**Comment by jtv** [comment]
It all depends.  If threading is the problem, 7.x can build without thread support.  In 6.4 I think you could just remove the two instances of the keyword `thread_local` in src/strconv.cxx, and it'll be slower but still work otherwise.

**Comment by jtv** [comment]
@yscontrol are we done with this ticket?  I'm trying to clean up a bit so we can keep a good overview of what the problems are.

**Comment by yscontrol** [comment]
Thank you for your support, but based on more resent attempts to build with different buuld parameters I think suggested code change (Yes. replace #define PQXX_NOVTABLE __declspec(novtable) with#define PQXX_NOVTABLE.) would be unnecesary
